# Generated by Django 4.2.29 on 2026-03-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpass", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outpass",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="outpass_images/"),
        ),
        migrations.AddField(
            model_name="outpass",
            name="purpose",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outpass",
            name="time_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
