# Generated by Django 4.2.29 on 2026-03-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outpass", "0002_outpass_image_outpass_purpose_outpass_time_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="outpass",
            name="hostel_status",
            field=models.CharField(
                choices=[("inside", "Inside Hostel"), ("outside", "Outside Hostel")],
                default="inside",
                max_length=20,
            ),
        ),
    ]
